### PR TITLE
separate function to connect to zk cluster, class-load dependency

### PR DESCRIPTION
**Pull request by rivik**
for more convenient use in applications

### CODE REVIEW

**Comment by komarov** [comment]
Hi Ilya, could you please describe the use case when it's needed?
Is it for overriding the method in a subclass?

About Class::Load dependency -- it seems like the module doesn't require it explicitly. Why do we need to add it?

**Comment by rivik** [comment]
Class::Load - yep, switchman doesn't require it, my fault. Actually, it's missing dependency in unofficial debian build of liblog-dispatch-perl 2.40-1 (http://backpan.perl.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.40.meta), nevermind =)

> could you please describe the use case when it's needed

To use same arguments/config parsing code in external monitoring tools, for example, get all locks in switchman group:

`my $sw = App::Switchman->new([@ARGV, "fake_cmd"]);
$sw->zk_connect();
print join "\n", $sw->zkh->get_children(join '/', $sw->prefix, $App::Switchman::LOCKS_PATH);`

**Comment by komarov** [comment]
Sorry for a delay with the answer, I was away for some time.

I think this functionality makes sense. If you could create a separate pr, it would be easier for me.

**Comment by komarov** [comment]
thanks, I've just uploaded a new version to cpan

**Pull request closed without merging**
